// src/applicants/applicants.service.ts

import {
  Injectable,
  BadRequestException,
  ConflictException,
  InternalServerErrorException,
  UnauthorizedException,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { JwtService } from '@nestjs/jwt';
import { SupabaseService } from '../supabase/supabase.service';
import { MailService } from '../mail/mail.service';
import { CreateApplicantDto } from './dto/create-applicant.dto';
import { ApplicantLoginDto } from './dto/applicant-login.dto';
import * as bcrypt from 'bcryptjs';
import * as crypto from 'crypto';

@Injectable()
export class ApplicantsService {
  constructor(
    private readonly supabaseService: SupabaseService,
    private readonly mailService: MailService,
    private readonly config: ConfigService,
    private readonly jwtService: JwtService,
  ) {}

  async register(dto: CreateApplicantDto) {
    const supabase = this.supabaseService.getClient();

    // 1. Check for duplicate email
    const { data: existing } = await supabase
      .from('applicant_profile')      // ← use the applicant-specific table
      .select('applicant_id')
      .eq('email', dto.email)
      .maybeSingle();

    if (existing) {
      throw new ConflictException('An account with this email already exists.');
    }

    // 2. Hash the password — same salt rounds as auth.service.ts (12)
    const password_hash = await bcrypt.hash(dto.password, 12);

    // 3. Generate unique IDs
    const applicant_id = crypto.randomUUID();
    const applicant_code = `APP-${Math.floor(1000000 + Math.random() * 9000000)}`;

    // 4. Insert the applicant — role and status are always set server-side
    const { error: insertError } = await supabase
      .from('applicant_profile')
      .insert({
        applicant_id,
        applicant_code,
        first_name: dto.first_name,
        last_name: dto.last_name,
        email: dto.email,
        phone_number: dto.phone_number ?? null,
        password_hash,               // hashed — never store plaintext
        role: 'Applicant',           // always hardcoded, never from request
        status: 'unverified',        // always hardcoded, verified after email click
        created_at: new Date().toISOString(),
      });

    if (insertError) throw new InternalServerErrorException(insertError.message);

    // 5. Generate email verification token (raw → email, hashed → DB)
    const rawToken = crypto.randomBytes(32).toString('hex');
    const tokenHash = crypto.createHash('sha256').update(rawToken).digest('hex');
    const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(); // 24hr

    const { error: tokenError } = await supabase
      .from('email_verifications')
      .insert({
        applicant_id,
        token_hash: tokenHash,
        expires_at: expiresAt,
        // verification_id, created_at auto-generated by DB; used_at set on verify
      });

    if (tokenError) throw new InternalServerErrorException(tokenError.message);

    // 6. Send verification email
    const appUrl = this.config.get<string>('APP_URL') ?? 'http://localhost:3000';
    const verifyLink = `${appUrl}/applicant/verify-email?token=${rawToken}`;

    try {
      await this.mailService.sendVerificationEmail(dto.email, verifyLink);
    } catch {
      // DEV fallback — log to terminal if email service fails (e.g. unverified Resend domain)
      console.log('==========================================');
      console.log('DEV MODE — verification link:');
      console.log(verifyLink);
      console.log('==========================================');
    }

    // 7. Return only safe fields — NEVER return password_hash
    return {
      applicant_id,
      applicant_code,
      email: dto.email,
      first_name: dto.first_name,
      last_name: dto.last_name,
      message: 'Account created. Please check your email to verify your address.',
    };
  }

  async verifyEmail(token: string) {
    if (!token) throw new BadRequestException('Verification token is required');

    const supabase = this.supabaseService.getClient();
    const tokenHash = crypto.createHash('sha256').update(token).digest('hex');

    // 1. Find the token record
    const { data: record, error } = await supabase
      .from('email_verifications')
      .select('verification_id, applicant_id, expires_at, used_at')
      .eq('token_hash', tokenHash)
      .maybeSingle();

    if (error || !record) throw new UnauthorizedException('Invalid or expired verification link');
    if (record.used_at) throw new UnauthorizedException('This verification link has already been used');
    if (new Date(record.expires_at) <= new Date()) throw new UnauthorizedException('This verification link has expired');

    // 2. Mark token as consumed
    await supabase
      .from('email_verifications')
      .update({ used_at: new Date().toISOString() })
      .eq('verification_id', record.verification_id);

    // 3. Activate the applicant account
    await supabase
      .from('applicant_profile')
      .update({ status: 'active' })
      .eq('applicant_id', record.applicant_id);

    return { message: 'Email verified successfully. You can now sign in.' };
  }

  async login(dto: ApplicantLoginDto) {
    const supabase = this.supabaseService.getClient();

    // 1. Find applicant by email
    const { data: applicant, error } = await supabase
      .from('applicant_profile')
      .select('applicant_id, email, password_hash, first_name, last_name, status')
      .eq('email', dto.email)
      .maybeSingle();

    if (error || !applicant) throw new UnauthorizedException('User not found');

    // 2. Block unverified accounts
    if (applicant.status === 'unverified') {
      throw new UnauthorizedException('Please verify your email before signing in.');
    }

    // 3. Check password
    const isMatch = await bcrypt.compare(dto.password, applicant.password_hash);
    if (!isMatch) throw new UnauthorizedException('Invalid credentials');

    // 4. Issue access token — no refresh session for applicants (stateless for now)
    const access_token = await this.jwtService.signAsync(
      {
        type: 'access',
        sub_userid: applicant.applicant_id,
        role_name: 'Applicant',
        first_name: applicant.first_name,
        last_name: applicant.last_name,
      },
      { expiresIn: '8h' },
    );

    return { access_token };
  }
}
